feat: :sparkles: updates schema to allow multiple maven artifacts
adobe/reactor-turbine-schemas pull request #37
Opened 2022-12-12 20:11 UTC by dsoffiantini

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Do these changes need to be released within a particular timeframe?

## Would there be any problems if we released these changes immediately?

## Do you foresee yourself proposing other known changes soon?

## Do these changes need to be coordinated with changes in other repositories?

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-12-16 21:41 UTC, dgrossen approved these changes

2023-01-05 23:25 UTC, dgrossen commented
@jeffreywalter when should we plan on this to be merged in and deployed?

2023-01-17 22:39 UTC, dgrossen commented on schemas/extension-package-mobile.json
> +                "$ref": "#/definitions/mavenFQArtifactName"
Shouldn't it be className that is an array? I don't think we want artifacts as an array

2023-01-17 22:40 UTC, dgrossen requested changes
Please look at the new Maven repo object

2023-01-17 23:01 UTC, dgrossen commented
Just change `artifact` to `artifacts` when it's an array and then I think it's good

2023-01-18 20:10 UTC, dgrossen approved these changes

2023-01-18 21:31 UTC, brenthosie approved these changes

2023-01-18 21:31 UTC, merged